DELETE FROM  DM_STREAM_RESTART WHERE COD_PROC_NAME IN ('FFT003','FFT004','FFT005','FFT007','JKW012','SEC001','FFT001')
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT003',1,'C','INST1',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT004',1,'C','INST1',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT004',2,'C','INST2',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT004',3,'C','INST1',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT004',4,'C','INST2',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT004',5,'C','INST1',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT004',6,'C','INST2',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT004',7,'C','INST1',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT004',8,'C','INST2',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT005',1,'C','INST1',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT005',2,'C','INST2',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT005',3,'C','INST1',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT005',4,'C','INST2',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT005',5,'C','INST1',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT005',6,'C','INST2',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT005',7,'C','INST1',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT005',8,'C','INST2',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT007',1,'C','INST1',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT007',2,'C','INST2',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT007',3,'C','INST1',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT007',4,'C','INST2',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT007',5,'C','INST1',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT007',6,'C','INST2',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT007',7,'C','INST1',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT007',8,'C','INST2',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('JKW012',1,'C','INST1',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('JKW012',2,'C','INST2',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('JKW012',3,'C','INST1',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('JKW012',4,'C','INST2',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('JKW012',5,'C','INST1',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('JKW012',6,'C','INST2',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('JKW012',7,'C','INST1',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('JKW012',8,'C','INST2',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('SEC001',1,'C','INST1',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('SEC001',2,'C','INST2',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('SEC001',3,'C','INST1',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('SEC001',4,'C','INST2',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('SEC001',5,'C','INST1',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('SEC001',6,'C','INST2',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('SEC001',7,'C','INST1',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('SEC001',8,'C','INST2',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT001',1,'C','INST1',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT001',2,'C','INST2',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT001',3,'C','INST1',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT001',4,'C','INST2',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT001',5,'C','INST1',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT001',6,'C','INST2',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT001',7,'C','INST1',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_STREAM_RESTART( COD_PROC_NAME,COD_STREAM,COD_STATUS,NAM_DBINSTANCE,DAT_LAST_RUN) 
VALUES('FFT001',8,'C','INST2',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/