DROP DIRECTORY FFT003-
/
CREATE DIRECTORY FFT003 AS '/datamigration/output/'
/
GRANT READ, WRITE, EXECUTE ON DIRECTORY FFT003 TO SYS
/
DROP DIRECTORY FFT004
/
CREATE DIRECTORY FFT004 AS '/datamigration/output/'
/
GRANT READ, WRITE, EXECUTE ON DIRECTORY FFT004 TO SYS
/
DROP DIRECTORY FFT005
/
CREATE DIRECTORY FFT005 AS '/datamigration/output/'
/
GRANT READ, WRITE, EXECUTE ON DIRECTORY FFT005 TO SYS
/
DROP DIRECTORY FFT007
/
CREATE DIRECTORY FFT007 AS '/datamigration/output/'
/
GRANT READ, WRITE, EXECUTE ON DIRECTORY FFT007 TO SYS
/
DROP DIRECTORY JKW012
/
CREATE DIRECTORY JKW012 AS '/datamigration/output/'
/
GRANT READ, WRITE, EXECUTE ON DIRECTORY JKW012 TO SYS
/
DROP DIRECTORY SEC001
/
CREATE DIRECTORY SEC001 AS '/datamigration/output/'
/
GRANT READ, WRITE, EXECUTE ON DIRECTORY SEC001 TO SYS
/
DROP DIRECTORY FFT001
/
CREATE DIRECTORY FFT001 AS '/datamigration/output/'
/
GRANT READ, WRITE, EXECUTE ON DIRECTORY FFT001 TO SYS
/