DELETE FROM  DM_STREAM_CTRL WHERE COD_PROC_NAME IN ('FFT003','FFT004','FFT005','FFT007','JKW012','SEC001','FFT001')
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT003',1,1)   
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT004',1,1)   
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT004',101,2)   
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT004',102,3)    
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT004',103,4)    
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT004',104,5)    
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT004',105,6)    
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT004',106,7)    
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT004',107,8)    
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT005',1,1)   
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT005',101,2)   
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT005',102,3)    
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT005',103,4)    
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT005',104,5)    
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT005',105,6)    
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT005',106,7)    
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT005',107,8)    
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT007',1,1)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT007',101,2)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT007',102,3)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT007',103,4)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT007',104,5)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT007',105,6)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT007',106,7)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT007',107,8)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('JKW012',1,1)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('JKW012',101,2)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('JKW012',102,3)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('JKW012',103,4)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('JKW012',104,5)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('JKW012',105,6)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('JKW012',106,7)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('JKW012',107,8)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('SEC001',1,1)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('SEC001',101,2)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('SEC001',102,3)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('SEC001',103,4)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('SEC001',104,5)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('SEC001',105,6)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('SEC001',106,7)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('SEC001',107,8)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT001',1,1)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT001',101,2)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT001',102,3)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT001',103,4)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT001',104,5)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT001',105,6)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT001',106,7)
/
INSERT INTO DM_STREAM_CTRL(COD_PROC_NAME,COD_CC_BRN,COD_STREAM) 
VALUES('FFT001',107,8)
/