DELETE FROM  DM_FILE_CONFIG  WHERE  COD_PROC_NAME IN ('FFT003','FFT004','FFT005','FFT007','JKW012','SEC001','FFT001')
/
INSERT INTO DM_FILE_CONFIG(COD_PROC_NAME,NAM_EXTRACT_FILE,DATE_START,DATE_END,FLG_DEFAULT_RUN,TABLE_NAME,DELIMITER,DIRECTORY_NAME,REC_SORT_ORDER,REC_SORT_KEY_ID) 
VALUES('FFT003','FFT003_000_001.dat','','','N','TBL_JBKDM_FFT003','','FFT003','','')  ; 
/
INSERT INTO DM_FILE_CONFIG(COD_PROC_NAME,NAM_EXTRACT_FILE,DATE_START,DATE_END,FLG_DEFAULT_RUN,TABLE_NAME,DELIMITER,DIRECTORY_NAME,REC_SORT_ORDER,REC_SORT_KEY_ID) 
VALUES('FFT004','FFT004_000_001.dat','','','N','TBL_JBKDM_FFT004','','FFT004','','')   
/
INSERT INTO DM_FILE_CONFIG(COD_PROC_NAME,NAM_EXTRACT_FILE,DATE_START,DATE_END,FLG_DEFAULT_RUN,TABLE_NAME,DELIMITER,DIRECTORY_NAME,REC_SORT_ORDER,REC_SORT_KEY_ID) 
VALUES('FFT005','FFT005_000_001.dat','','','N','TBL_JBKDM_FFT005','','FFT005','','')   ;
/
INSERT INTO DM_FILE_CONFIG(COD_PROC_NAME,NAM_EXTRACT_FILE,DATE_START,DATE_END,FLG_DEFAULT_RUN,TABLE_NAME,DELIMITER,DIRECTORY_NAME,REC_SORT_ORDER,REC_SORT_KEY_ID) 
VALUES('FFT007','FFT007_000_001.dat','','','N','TBL_JBKDM_FFT007','','FFT007','','')
/
INSERT INTO DM_FILE_CONFIG(COD_PROC_NAME,NAM_EXTRACT_FILE,DATE_START,DATE_END,FLG_DEFAULT_RUN,TABLE_NAME,DELIMITER,DIRECTORY_NAME,REC_SORT_ORDER,REC_SORT_KEY_ID) 
VALUES('JKW012','JKW012_000_001.dat','','','N','TBL_JBKDM_JKW012','','JKW012','','')
/
INSERT INTO DM_FILE_CONFIG(COD_PROC_NAME,NAM_EXTRACT_FILE,DATE_START,DATE_END,FLG_DEFAULT_RUN,TABLE_NAME,DELIMITER,DIRECTORY_NAME,REC_SORT_ORDER,REC_SORT_KEY_ID) 
VALUES('SEC001','SEC001_000_001.dat','','','N','TBL_JBKDM_SEC001','','SEC001','','')
/
INSERT INTO DM_FILE_CONFIG(COD_PROC_NAME,NAM_EXTRACT_FILE,DATE_START,DATE_END,FLG_DEFAULT_RUN,TABLE_NAME,DELIMITER,DIRECTORY_NAME,REC_SORT_ORDER,REC_SORT_KEY_ID) 
VALUES('FFT001','FFT001_000_001.dat','','','N','TBL_JBKDM_FFT001','','FFT001','','')
/


DELETE FROM  DM_FILE_CONFIG  WHERE  COD_PROC_NAME IN ('FFT003','FFT004','FFT005','FFT007','JKW012','SEC001','FFT001')/INSERT INTO DM_FILE_CONFIG(COD_PROC_NAME,NAM_EXTRACT_FILE,DATE_START,DATE_END,FLG_DEFAULT_RUN,TABLE_NAME,DELIMITER,DIRECTORY_NAME,REC_SORT_ORDER,REC_SORT_KEY_ID) VALUES('FFT003','FFT003_000_001.dat','','','N','TBL_JBKDM_FFT003','','FFT003','','')  ;/INSERT INTO DM_FILE_CONFIG(COD_PROC_NAME,NAM_EXTRACT_FILE,DATE_START,DATE_END,FLG_DEFAULT_RUN,TABLE_NAME,DELIMITER,DIRECTORY_NAME,REC_SORT_ORDER,REC_SORT_KEY_ID) VALUES('FFT004','FFT004_000_001.dat','','','N','TBL_JBKDM_FFT004','','FFT004','','')   /INSERT INTO DM_FILE_CONFIG(COD_PROC_NAME,NAM_EXTRACT_FILE,DATE_START,DATE_END,FLG_DEFAULT_RUN,TABLE_NAME,DELIMITER,DIRECTORY_NAME,REC_SORT_ORDER,REC_SORT_KEY_ID) VALUES('FFT005','FFT005_000_001.dat','','','N','TBL_JBKDM_FFT005','','FFT005','','')   ;/INSERT INTO DM_FILE_CONFIG(COD_PROC_NAME,NAM_EXTRACT_FILE,DATE_START,DATE_END,FLG_DEFAULT_RUN,TABLE_NAME,DELIMITER,DIRECTORY_NAME,REC_SORT_ORDER,REC_SORT_KEY_ID) VALUES('FFT007','FFT007_000_001.dat','','','N','TBL_JBKDM_FFT007','','FFT007','','')/INSERT INTO DM_FILE_CONFIG(COD_PROC_NAME,NAM_EXTRACT_FILE,DATE_START,DATE_END,FLG_DEFAULT_RUN,TABLE_NAME,DELIMITER,DIRECTORY_NAME,REC_SORT_ORDER,REC_SORT_KEY_ID) VALUES('JKW012','JKW012_000_001.dat','','','N','TBL_JBKDM_JKW012','','JKW012','','')/INSERT INTO DM_FILE_CONFIG(COD_PROC_NAME,NAM_EXTRACT_FILE,DATE_START,DATE_END,FLG_DEFAULT_RUN,TABLE_NAME,DELIMITER,DIRECTORY_NAME,REC_SORT_ORDER,REC_SORT_KEY_ID) VALUES('SEC001','SEC001_000_001.dat','','','N','TBL_JBKDM_SEC001','','SEC001','','')/INSERT INTO DM_FILE_CONFIG(COD_PROC_NAME,NAM_EXTRACT_FILE,DATE_START,DATE_END,FLG_DEFAULT_RUN,TABLE_NAME,DELIMITER,DIRECTORY_NAME,REC_SORT_ORDER,REC_SORT_KEY_ID) VALUES('FFT001','FFT001_000_001.dat','','','N','TBL_JBKDM_FFT001','','FFT001','','')/