DELETE FROM  DM_FILE_RUN_STATUS WHERE COD_PROC_NAME IN ('FFT003','FFT004','FFT005','FFT007','JKW012','SEC001','FFT001')
/
INSERT INTO DM_FILE_RUN_STATUS(NAM_EXTRACT_FILE,COD_STATUS,COD_PROC_NAME,CNT_TOTAL_REC,DAT_TIME_START,DAT_TIME_END,DAT_LAST_RUN) 
VALUES('FFT003_000_001.dat','C','FFT003',0,'','',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_FILE_RUN_STATUS(NAM_EXTRACT_FILE,COD_STATUS,COD_PROC_NAME,CNT_TOTAL_REC,DAT_TIME_START,DAT_TIME_END,DAT_LAST_RUN) 
VALUES('FFT004_000_001.dat','C','FFT004',0,'','',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_FILE_RUN_STATUS(NAM_EXTRACT_FILE,COD_STATUS,COD_PROC_NAME,CNT_TOTAL_REC,DAT_TIME_START,DAT_TIME_END,DAT_LAST_RUN) 
VALUES('FFT005_000_001.dat','C','FFT005',0,'','',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_FILE_RUN_STATUS(NAM_EXTRACT_FILE,COD_STATUS,COD_PROC_NAME,CNT_TOTAL_REC,DAT_TIME_START,DAT_TIME_END,DAT_LAST_RUN) 
VALUES('FFT007_000_001.dat','C','FFT007',0,'','',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_FILE_RUN_STATUS(NAM_EXTRACT_FILE,COD_STATUS,COD_PROC_NAME,CNT_TOTAL_REC,DAT_TIME_START,DAT_TIME_END,DAT_LAST_RUN) 
VALUES('JKW012_000_001.dat','C','JKW012',0,'','',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_FILE_RUN_STATUS(NAM_EXTRACT_FILE,COD_STATUS,COD_PROC_NAME,CNT_TOTAL_REC,DAT_TIME_START,DAT_TIME_END,DAT_LAST_RUN) 
VALUES('SEC001_000_001.dat','C','SEC001',0,'','',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
INSERT INTO DM_FILE_RUN_STATUS(NAM_EXTRACT_FILE,COD_STATUS,COD_PROC_NAME,CNT_TOTAL_REC,DAT_TIME_START,DAT_TIME_END,DAT_LAST_RUN) 
VALUES('FFT001_000_001.dat','C','FFT001',0,'','',PK_BA_GLOBAL.DAT_LAST_PROCESS)   
/
